#!/usr/bin/env python3
import os
import sys
src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if src_path not in sys.path:
    sys.path.append(src_path)
#!/usr/bin/env python3

from types import MethodType
import requests
import client


def main():
    try:
        state, args = client.parse_args()
        res = requests.get(f"http://{state['REP_ADDRESS']}/org/", json=args)

        # pretty print the response
        for org in res.json():
            print(f"Organization: {org['name']}")
            print(f"Subjects: {org['subject']}")
            print(f"Documents: {org['documents']}")
            print("")
    except Exception as e:
        client.logger.error(f"Error in main: {e}")
        return 1

    return 0


if __name__ == "__main__":
    main()
